version: '3.5'
services:
  ms:
    build: .
    image: fiap-covid-api:latest
    container_name: fiap-covid-api
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      ENV: local
      DB_HOST_NAME: fiap-covid-db
      DB_PORT: 5432
      DB_NAME: fiap
      DB_USERNAME: fiap
      DB_PASSWORD: fiap
    networks:
      - fiap-network
  db:
    image: kartoza/postgis
    container_name: fiap-covid-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_PASS=fiap
      - POSTGRES_DBNAME=fiap
    volumes:
      - fiap-volume:/var/lib/postgresql
    networks:
      - fiap-network
networks:
  fiap-network:
    name: fiap-network
volumes:
  fiap-volume:
    driver: local
